### ISSUE TITLE
The backfiles are missing

### ISSUE THREAD

**Issue by sinamr88** [ethz-asl/yumi#14]
Hi All,

I was following the wiki to set-up our YuMi and, first of all I need to thank you all for proving this wiki. Apparently, non of the links of the back-up files, mentioned in https://github.com/ethz-asl/yumi/wiki/Setting-Up-YuMi-in-RobotStudio, works. It would be great if you guys can help. 

Best
Sina

**Comment by FWachter** [comment]
Hello Sina,

The system backup files are there, but they haven't been merged into the master branch and are still in the [addition/demo](https://github.com/ethz-asl/yumi/tree/addition/Demo) branch. The system backup files can be found [here](https://github.com/ethz-asl/yumi/tree/addition/Demo/yumi_support/system_backups). Let me know if this solves the issue.

Thanks,
Freddy W.

**Comment by sinamr88** [comment]
Hi Freddy,

Thx  a lot for your help..:)

Best,
Sina
